name: CI

on:
  push:
    branches:
      - next

  pull_request:
    branches:
      - next

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install pnpm
      run: corepack enable

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run test cases
      run: |
          echo "pull request: $GITHUB_BASE_REF $GITHUB_HEAD_REF"
          git fetch origin $GITHUB_BASE_REF:$GITHUB_BASE_REF
          git fetch origin $GITHUB_HEAD_REF:$GITHUB_HEAD_REF
          git checkout $GITHUB_HEAD_REF
          DIFF=$(git diff --name-only $GITHUB_BASE_REF..$GITHUB_HEAD_REF)
          echo "changed files: $DIFF"
          COMPONENT=$(echo "$DIFF" |  grep -E -i 'src\/packages\/([a-z]+)(\/[a-z_\.]*)*' | sed -E 's/src\/packages\/([a-z]+)(\/[a-z_\.]*)*/\1/i' | awk 'END{print}')
          npm test -- $COMPONENT

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install pnpm
      run: corepack enable

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build NutUI-React
      run: npm run build

    - name: Build NutUI-React-Taro
      run: npm run build:taro
    
    - name: Build NutUI-React Demo
      run: npm run build:site
